#:import SettingsScreen modules.moduleSettings.settings.SettingsScreen
<SettingsScreen>:
    BoxLayout:
        orientation:'vertical'
        MDTopAppBar:
                title:"Carrito De Ventas"
                icon:"shopping"
                left_action_items:
                    [
                    ["card-search", lambda x: root.openMainScreen(),  "Buscar Articulo"]
                    ]
        